# Generated by Django 3.0.6 on 2020-05-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0018_standardize_description'),
        ('payment', '0003_payment_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),

        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='sub_project',
            field=models.CharField(blank=True, default='Студия', max_length=70),
        ),
        migrations.AddField(
            model_name='payment',
            name='work_description',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='payment',
            name='contractor',
            field=models.ForeignKey(blank=True, default='null', on_delete=django.db.models.deletion.PROTECT, to='payment.Contractor'),
        ),
    ]
