# Generated by Django 3.0.6 on 2020-05-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='contractor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='payment.Contractor'),
        ),
    ]
